### ISSUE TITLE
Crash on connection reset

### ISSUE THREAD

**Issue by marcocipriani01** [INDIForJava/INDIForJava#24]
```
E/AndroidRuntime: FATAL EXCEPTION: client reader indi://192.168.1.2:7624/
    Process: marcocipriani01.iparcos, PID: 10380
    com.thoughtworks.xstream.io.StreamException:  : Connection reset
        at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87)
        at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:1847)
        at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:120)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:421)
        at org.indilib.i4j.protocol.io.INDIInputStreamImpl.readObject(INDIInputStreamImpl.java:83)
        at org.indilib.i4j.INDIProtocolReader.run(INDIProtocolReader.java:78)
     Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:215)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at org.indilib.i4j.protocol.io.MinimalBlockinInputStream.read(MinimalBlockinInputStream.java:69)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
        at java.io.SequenceInputStream.read(SequenceInputStream.java:207)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.io.PushbackInputStream.read(PushbackInputStream.java:186)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.read(XmlHeaderAwareReader.java:223)
        at com.android.org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1516)
        at com.android.org.kxml2.io.KXmlParser.peekType(KXmlParser.java:993)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148) 
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135) 
        at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87) 
        at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:1847) 
        at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:120) 
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:421) 
        at org.indilib.i4j.protocol.io.INDIInputStreamImpl.readObject(INDIInputStreamImpl.java:83) 
        at org.indilib.i4j.INDIProtocolReader.run(INDIProtocolReader.java:78) 
I/Process: Sending signal. PID: 10380 SIG: 9

```

**Comment by theChef613** [comment]
Not 100% sure this is the same issue but I'm having a simmilar issue using API 30 but a different debugger output.
The app crashes when I select an ip address that does not have an associated INDI server. below is the debugger reply:
`E/AndroidRuntime: FATAL EXCEPTION: client reader indi://192.168.10.111:7624/
    Process: marcocipriani01.iparcos, PID: 14221
    java.lang.NullPointerException: Attempt to invoke interface method 'void org.indilib.i4j.protocol.api.INDIInputStream.close()' on a null object reference
        at org.indilib.i4j.INDIProtocolReader.run(INDIProtocolReader.java:84)`

**Comment by marcocipriani01** [comment]
Thank you for your report! I think I've fixed both errors, I'm now testing IPARCOS to see if it happens again.

**Comment by theChef613** [comment]
confirmed fixed for my issue as well!

**Comment by marcocipriani01** [comment]
Great! As far as IPARCOS is concerned, expect soon some new features in the focuser module:

![Screenshot_20201231-181425_IPARCOS.jpg](https://user-images.githubusercontent.com/20319029/103419753-a6c36b80-4b94-11eb-9306-4518e96ae717.jpg)

After that I will be releasing the app on the Google Play Store.

**Comment by theChef613** [comment]
awesome! i tried sending you a private message though your website. hopefully you'll get it.
